account/wallet.go
go.mod
schnorr/schnorr.go

This pr is to improve sinning  procedure, avoid potential stuck issue by using golang internal left padding function rather than using for loop to get correct one.

Improve signing procedure 

---

README.md
account/wallet.go
account/wallet_test.go
contract/contract.go
contract/contract_test.go
provider/provider.go
provider/provider_test.go
provider/transaction_payload_test.go
subscription/chainwalker.go
transaction/transaction.go

This pr is to enhance exist API calls, especially fix a potential NPE. FIx some unit tests and documentation.

Enhance api calls, add more documents.

---

.github/workflows/ci.yml
Dockerfile

Setup GitHub actions for ci purpose.

Setup GitHub actions

---

provider/provider.go
provider/provider_test.go

This PR is to support api `GetTxnBodiesForTxBlock`.

feat(provider): support api GetTxnBodiesForTxBlock

---

provider/provider.go
provider/provider_test.go

This PR is to support API `GetMinerInfo`.

feat(provider): support GetMinerInfo api

---

provider/provider.go

This PR is to support API [getpendingtxn](https://apidocs.zilliqa.com/#getpendingtxn)

feat(provider): support GetPendingTxns

---

account/wallet.go

This pr is to support batch signing started from a specific nonce.

feat: support batch signning started from specific nonce

---

core/types.go

fix: transaction receipt type

---

provider/provider.go
provider/provider_test.go

fix: get contract address from transaction id

---

provider/provider.go

fix: some rpc error

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

To add PR template and issue template to the repository.

chore: add issue template and PR template

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
core/types.go
provider/provider.go
provider/provider_test.go

This PR introduces following features/fixes:
1. Batch rpc for `GetTransaction` to enable users to confirm multiple transactions with only one request.
2. Fix GetPendingTxns 
3. Introduce PR template and issue template

Merge from dev

---

core/types.go

To fix a field name inside transaction receipt.

fix: correct field name

---

account/wallet_test.go
contract/contract.go
contract/contract_test.go
core/types.go
provider/transaction_payload.go
provider/transaction_payload_test.go
transaction/transaction.go
transaction/transaction_test.go

fix(payload): add payment type

---

account/wallet_test.go
contract/contract.go
contract/contract_test.go
core/types.go
provider/transaction_payload.go
provider/transaction_payload_test.go
transaction/transaction.go
transaction/transaction_test.go

This PR introduces following changes:
1. Fix an error for transaction receipt
2. Provide a new function to compute (signing) transaction hash locally.
3. Support two new types for constructing transaction payload (further constructing transaction struct) from json file: payment transaction type and contract deployment transaction type.
4. Fix some unit tests.

Merge from develop

---

account/wallet_test.go
contract/contract.go
contract/contract_test.go
core/types.go

This PR introduces following changes:
1. Add a new function to simplify contract deployment and call (to mainnet, testnet and isolated server) by using default parameters including chain id, message version and gas fee.
2. Add a new type to construct complex scilla data type.

feat: shortcut functions for smart contract

---

keytools/secp256k1.go
schnorr/schnorr.go
schnorr/schnorr_test.go

To fix schnorr verify function, and redo private key generation.

fix: private key generation, schnorr verify

---

keytools/secp256k1.go
schnorr/schnorr.go
schnorr/schnorr_signer_wrapper.go

Remove some unnecessary print in order to not break the test of other tools (like rostta).

chore: remove some print

---

keytools/secp256k1.go
schnorr/schnorr.go
schnorr/schnorr_signer_wrapper.go
util/util.go

merge from master

---

prover/prover.go

fix(prover): use hashed storage key

---

crosschain/polynetwork/lock_proxy.go

Fix transition name for calling LockProxy contract

fix(crosschain): transition name

---

crosschain/polynetwork/cross_chain_manager.go
crosschain/polynetwork/lock_proxy.go
crosschain/polynetwork/proof.go
crosschain/polynetwork/safe_math.go
crosschain/polynetwork/util.go
crosschain/polynetwork/util_test.go
crosschain/polynetwork/zero_copy_source.go

feat(crosschain): add new transitions

---

core/dsblock_header.go

This PR it to fix the serializing issue of ds block.

fix: serializing issue

---

core/common.go
core/dsblock_header.go
core/txblock.go
verifier/verifier.go

fix: pow winner order
